/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Readiness, including the migration the database is actually on.
         *
         *     The schema version matters: an API serving a database one migration behind
         *     will fail in ways that look like data problems rather than deployment ones.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/processes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Processes */
        get: operations["list_processes_api_processes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/processes/{process_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Process */
        get: operations["get_process_api_processes__process_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/processes/{process_id}/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * State History
         * @description Append-only State history — the sequence *is* the record (ui_concept §32).
         */
        get: operations["state_history_api_processes__process_id__states_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/processes/{process_id}/journal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Journal
         * @description Why the system changed its mind, chronologically (PRD §21).
         */
        get: operations["journal_api_processes__process_id__journal_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/processes/{process_id}/critiques": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Critiques
         * @description Adversarial findings, including superseded ones.
         *
         *     Addressed critiques are returned rather than hidden: a thesis that survived
         *     four attacks is stronger than one never attacked, and that is only visible
         *     if the attacks remain on the record.
         */
        get: operations["critiques_api_processes__process_id__critiques_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event */
        get: operations["get_event_api_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Evidence Trail
         * @description Trace a node back through Events and Claims to its documents.
         */
        get: operations["evidence_trail_api_evidence__node_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bottlenecks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bottlenecks */
        get: operations["list_bottlenecks_api_bottlenecks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bottlenecks/{bottleneck_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bottleneck */
        get: operations["get_bottleneck_api_bottlenecks__bottleneck_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bottlenecks/{bottleneck_id}/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Requirements
         * @description The AND/OR/optional structure that would resolve this constraint.
         */
        get: operations["get_requirements_api_bottlenecks__bottleneck_id__requirements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Capabilities */
        get: operations["list_capabilities_api_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capabilities/{capability_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Capability */
        get: operations["get_capability_api_capabilities__capability_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assets */
        get: operations["list_assets_api_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Asset */
        get: operations["get_asset_api_assets__asset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_id}/discovery-chain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discovery Chain
         * @description Every route from a Process down to this Asset, shortest first.
         */
        get: operations["discovery_chain_api_assets__asset_id__discovery_chain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/reach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Asset Reach
         * @description Assets reachable from these Processes, most-converged-on first.
         */
        get: operations["asset_reach_api_graph_reach_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/subgraph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Subgraph
         * @description Nodes and edges around a set of seeds, for the explorer (issue #26).
         */
        get: operations["subgraph_api_graph_subgraph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paths */
        get: operations["paths_api_graph_paths_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/integrity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Integrity
         * @description Structural checks Postgres cannot express (issue #13).
         *
         *     Exposed because the Research Quality Auditor (#57) and the eval harness both
         *     need it, and because a graph that has quietly acquired a causal cycle should
         *     be visible rather than discovered through a traversal that makes no sense.
         */
        get: operations["integrity_api_graph_integrity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scores/{subject_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scores
         * @description Scorecards for a subject, one family per card.
         *
         *     There is deliberately no endpoint that blends families: Thesis quality,
         *     Asset quality and Trade quality are separate by construction (ontology §17),
         *     and offering a combined number here would undo that at the last step.
         */
        get: operations["scores_api_scores__subject_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pipeline
         * @description The declared pipeline (issue #14).
         *
         *     ``has_handler`` and ``has_reconciler`` are reported rather than assumed: a
         *     stage with no handler never runs, and one with no reconciler has no backstop
         *     if its triggering event is lost.
         */
        get: operations["pipeline_api_pipeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Queue Depth */
        get: operations["queue_depth_api_pipeline_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentRunOut
         * @description The provenance record every derived row cites.
         */
        AgentRunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Agent Name */
            agent_name: string;
            /** Agent Version */
            agent_version: string;
            /** Ontology Layer */
            ontology_layer: string;
            /** Status */
            status: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Attempts */
            attempts: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cost Usd */
            cost_usd: number | null;
            /** Latency Ms */
            latency_ms: number | null;
            /** Evaluation */
            evaluation?: {
                [key: string]: unknown;
            } | null;
            /** Trigger Event Id */
            trigger_event_id?: string | null;
        };
        /**
         * AssetClass
         * @description Ontology §14. V1 expresses theses through the underlying asset only —
         *     options and derivatives are explicitly out of scope.
         * @enum {string}
         */
        AssetClass: "common_stock" | "etf" | "commodity" | "currency" | "bond" | "index";
        /** AssetDetailOut */
        AssetDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            asset_class: components["schemas"]["AssetClass"];
            identifiers: components["schemas"]["AssetIdentifiersOut"];
            /** Country */
            country: string | null;
            /** Currency */
            currency: string | null;
            /** Sector */
            sector: string | null;
            /** Industry */
            industry: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Discovery Chain
             * @description Why this Asset is in the graph (issue #28).
             */
            discovery_chain?: components["schemas"]["DiscoveryPathOut"][];
            /** Exposures */
            exposures?: components["schemas"]["ExposureOut"][];
        };
        /**
         * AssetIdentifiersOut
         * @description Not equity-only: a commodity carries a code and a benchmark, a currency a pair.
         */
        AssetIdentifiersOut: {
            /** Ticker */
            ticker?: string | null;
            /** Exchange */
            exchange?: string | null;
            /** Isin */
            isin?: string | null;
            /** Commodity Code */
            commodity_code?: string | null;
            /** Contract Code */
            contract_code?: string | null;
            /** Benchmark */
            benchmark?: string | null;
            /** Currency Pair */
            currency_pair?: string | null;
            /** Currency Code */
            currency_code?: string | null;
        };
        /** AssetOut */
        AssetOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            asset_class: components["schemas"]["AssetClass"];
            identifiers: components["schemas"]["AssetIdentifiersOut"];
            /** Country */
            country: string | null;
            /** Currency */
            currency: string | null;
            /** Sector */
            sector: string | null;
            /** Industry */
            industry: string | null;
            /** Is Active */
            is_active: boolean;
        };
        /** AssetReachOut */
        AssetReachOut: {
            asset: components["schemas"]["NodeRef"];
            /** Shortest Hops */
            shortest_hops: number;
            /** Distinct Source Count */
            distinct_source_count: number;
            /** Best Weight */
            best_weight: number;
            /** Paths */
            paths?: components["schemas"]["DiscoveryPathOut"][];
        };
        /**
         * BottleneckKind
         * @description Ontology §11 — what class of constraint blocks the Process.
         * @enum {string}
         */
        BottleneckKind: "physical_capacity" | "input_supply" | "processing_capacity" | "infrastructure" | "regulatory_permitting" | "capital" | "labor_skills" | "technology" | "logistics" | "other";
        /** BottleneckOut */
        BottleneckOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Process Id
             * Format: uuid
             */
            process_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            kind: components["schemas"]["BottleneckKind"];
            /**
             * Currently Binding
             * @description Whether it constrains the Process now, or would only later.
             */
            currently_binding: boolean;
            /** Demand Pressure */
            demand_pressure: number | null;
            /** Supply Elasticity */
            supply_elasticity: number | null;
            /** Time To Expand */
            time_to_expand: number | null;
            /** Current Constraint */
            current_constraint: number | null;
            /** Relief Indicators */
            relief_indicators?: string[];
            /** Confidence */
            confidence: number;
            /** Resolved */
            resolved: boolean;
        };
        /** CapabilityDetailOut */
        CapabilityDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description: string;
            /** Aliases */
            aliases?: string[];
            /**
             * Upstream Processes
             * @description Processes reaching this Capability. Several independent ones is confluence (ontology §13), read off the graph rather than asserted.
             */
            upstream_processes?: components["schemas"]["NodeRef"][];
            /** Expressed By */
            expressed_by?: components["schemas"]["NodeRef"][];
        };
        /** CapabilityOut */
        CapabilityOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description: string;
            /** Aliases */
            aliases?: string[];
        };
        /** ClaimOut */
        ClaimOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Text */
            text: string;
            /** Claim Type */
            claim_type: string;
            /** Assertion Source */
            assertion_source: string | null;
            /** Attributed To */
            attributed_to: string | null;
            /** Extraction Confidence */
            extraction_confidence: number;
            /**
             * Source Location
             * @description Verified span: the quote and its offsets in the parsed document.
             */
            source_location: {
                [key: string]: unknown;
            };
        };
        /**
         * CritiqueKind
         * @description The seven lines of attack the Process Critic must take (agent doc §6.5).
         *
         *     A closed vocabulary because the critic's coverage is measurable: an
         *     adversarial pass that only ever finds "contradictory evidence" is not
         *     attacking the thesis from seven directions.
         * @enum {string}
         */
        CritiqueKind: "unsupported_assumption" | "missing_causal_link" | "contradictory_evidence" | "alternative_explanation" | "historical_counterexample" | "falsifying_indicator" | "spurious_correlation";
        /** CritiqueOut */
        CritiqueOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["CritiqueKind"];
            /** Statement */
            statement: string;
            /** Severity */
            severity: number;
            /** Rationale */
            rationale: string;
            /** Testable With */
            testable_with: string | null;
            /** Is Most Damaging */
            is_most_damaging: boolean;
            status: components["schemas"]["CritiqueStatus"];
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
        };
        /**
         * CritiqueStatus
         * @description What became of a critique.
         *
         *     Critiques are never deleted. A thesis that survived an attack is stronger
         *     than one that was never attacked, and that is only visible if the attacks
         *     remain on the record.
         * @enum {string}
         */
        CritiqueStatus: "open" | "addressed" | "dismissed" | "confirmed";
        /**
         * Direction
         * @description Which way to walk the typed edges.
         *
         *     The canonical chain runs Process → Bottleneck → Capability → Asset, so
         *     ``DOWNSTREAM`` answers "what could express this Process" and ``UPSTREAM``
         *     answers "why is this Asset here" — the two questions the UI asks most.
         * @enum {string}
         */
        Direction: "downstream" | "upstream" | "both";
        /**
         * DiscoveryPathOut
         * @description One route from a Process down to an Asset, with the reason at each step.
         */
        DiscoveryPathOut: {
            start: components["schemas"]["NodeRef"];
            /** Steps */
            steps: components["schemas"]["PathStepOut"][];
            /** Depth */
            depth: number;
            /** Weight */
            weight: number;
        };
        /** DocumentOut */
        DocumentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source */
            source: string;
            /** Publisher */
            publisher: string | null;
            /** Title */
            title: string;
            /** Url */
            url: string | null;
            /** Document Type */
            document_type: string;
            /**
             * Publication Time
             * Format: date-time
             */
            publication_time: string;
            /** Storage Uri */
            storage_uri: string | null;
        };
        /**
         * EntityType
         * @description Node types in the economic graph.
         *
         *     Mirrors the top-level ontology chain (ontology §3). Every node registered in
         *     the graph declares one of these, which is what makes typed edges checkable.
         * @enum {string}
         */
        EntityType: "document" | "claim" | "event" | "process" | "bottleneck" | "capability" | "asset";
        /** EventDetailOut */
        EventDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            event_type: components["schemas"]["EventType"];
            /** Title */
            title: string;
            /** Description */
            description: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Independent Source Count
             * @description Distinct reports behind this Event after syndication collapse — not the document count (ontology §47).
             */
            independent_source_count: number;
            /** Novelty */
            novelty: number;
            /** Materiality */
            materiality: number;
            /** Confidence */
            confidence: number;
            /** Contradictions */
            contradictions?: string[];
            /**
             * Propagated At
             * @description When this Event cleared the significance gate. Null means it is accumulating.
             */
            propagated_at?: string | null;
            /** Revision */
            revision: number;
            /** Claims */
            claims?: components["schemas"]["ClaimOut"][];
            /** Documents */
            documents?: components["schemas"]["DocumentOut"][];
        };
        /** EventOut */
        EventOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            event_type: components["schemas"]["EventType"];
            /** Title */
            title: string;
            /** Description */
            description: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Independent Source Count
             * @description Distinct reports behind this Event after syndication collapse — not the document count (ontology §47).
             */
            independent_source_count: number;
            /** Novelty */
            novelty: number;
            /** Materiality */
            materiality: number;
            /** Confidence */
            confidence: number;
            /** Contradictions */
            contradictions?: string[];
            /**
             * Propagated At
             * @description When this Event cleared the significance gate. Null means it is accumulating.
             */
            propagated_at?: string | null;
            /** Revision */
            revision: number;
        };
        /**
         * EventType
         * @description Ontology §6. Coarse routing categories, not a taxonomy of the world.
         * @enum {string}
         */
        EventType: "policy_announcement" | "policy_enactment" | "regulatory_action" | "government_funding" | "corporate_action" | "guidance_change" | "capex_announcement" | "capacity_change" | "supply_disruption" | "demand_shift" | "price_move" | "technology_milestone" | "macro_policy" | "data_release" | "other";
        /**
         * EvidenceTrailOut
         * @description A statement traced to the documents behind it (agent doc §2.4).
         */
        EvidenceTrailOut: {
            subject: components["schemas"]["NodeRef"];
            /** Supporting Events */
            supporting_events?: components["schemas"]["NodeRef"][];
            /** Contradicting Events */
            contradicting_events?: components["schemas"]["NodeRef"][];
            /** Claim Ids */
            claim_ids?: string[];
            /** Document Ids */
            document_ids?: string[];
            /** Is Evidenced */
            is_evidenced: boolean;
        };
        /**
         * ExposureKind
         * @description Ontology §16 'Process Exposure' — how an Asset touches the Process.
         * @enum {string}
         */
        ExposureKind: "revenue" | "incremental_earnings" | "capacity" | "market_share" | "production_capability" | "strategic_positioning" | "geographic";
        /** ExposureOut */
        ExposureOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            target: components["schemas"]["NodeRef"];
            exposure_kind: components["schemas"]["ExposureKind"];
            /** Directness */
            directness: string;
            /** Magnitude */
            magnitude: number;
            /** Revenue Share */
            revenue_share: number | null;
            /**
             * Quantitative Basis
             * @description The figure a revenue share rests on, where one was supplied.
             */
            quantitative_basis?: string | null;
            /** Rationale */
            rationale: string;
            /** Confidence */
            confidence: number;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
        };
        /** GraphEdgeOut */
        GraphEdgeOut: {
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /**
             * Target Id
             * Format: uuid
             */
            target_id: string;
            relationship_type: components["schemas"]["RelationshipType"];
            /** Weight */
            weight: number;
            /** Confidence */
            confidence: number;
            /** Rationale */
            rationale?: string | null;
        };
        /** GraphNodeOut */
        GraphNodeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            type: components["schemas"]["EntityType"];
            /** Label */
            label: string;
            /** Slug */
            slug?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Database */
            database: boolean;
            /** Schema Version */
            schema_version?: string | null;
        };
        /** IntegrityReportOut */
        IntegrityReportOut: {
            /** Ok */
            ok: boolean;
            /** Checked At */
            checked_at: string | null;
            /** Violations */
            violations?: components["schemas"]["IntegrityViolationOut"][];
        };
        /** IntegrityViolationOut */
        IntegrityViolationOut: {
            /** Kind */
            kind: string;
            /** Node Id */
            node_id: string | null;
            /** Detail */
            detail: string;
        };
        /**
         * JournalEntryOut
         * @description Why the system changed its mind (PRD §21).
         */
        JournalEntryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Summary */
            summary: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Confidence Before */
            confidence_before: number | null;
            /** Confidence After */
            confidence_after: number | null;
            /** Changes */
            changes?: {
                [key: string]: unknown;
            }[];
            /** Triggering Event Id */
            triggering_event_id?: string | null;
        };
        /**
         * LogicOperator
         * @description Ontology §12 — Capability requirements form logical structures.
         * @enum {string}
         */
        LogicOperator: "and" | "or";
        /**
         * Necessity
         * @enum {string}
         */
        Necessity: "required" | "optional";
        /**
         * NodeRef
         * @description A pointer to any node, with enough to render it.
         */
        NodeRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            type: components["schemas"]["EntityType"];
            /** Label */
            label: string;
            /** Slug */
            slug?: string | null;
        };
        /** PathStepOut */
        PathStepOut: {
            relationship_type: components["schemas"]["RelationshipType"];
            /** Rationale */
            rationale: string | null;
            to: components["schemas"]["NodeRef"];
        };
        /** PipelineStageOut */
        PipelineStageOut: {
            /** Name */
            name: string;
            /** Priority */
            priority: number;
            /** Concurrency */
            concurrency: number;
            /** Triggered By */
            triggered_by: string[];
            /** Emits */
            emits: string[];
            /** Description */
            description: string;
            /** Has Handler */
            has_handler: boolean;
            /** Has Reconciler */
            has_reconciler: boolean;
        };
        /**
         * ProcessArchetype
         * @description Ontology §8. Each archetype has its own State machine — see
         *     ``econiq_ontology.archetypes``.
         * @enum {string}
         */
        ProcessArchetype: "infrastructure_s_curve" | "commodity_supply_cycle" | "industrial_bottleneck" | "regulatory_implementation" | "business_model_disruption";
        /** ProcessDetailOut */
        ProcessDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description: string;
            archetype: components["schemas"]["ProcessArchetype"] | null;
            /** Archetype Confidence */
            archetype_confidence: number | null;
            status: components["schemas"]["ProcessStatus"];
            /** Requires Review */
            requires_review: boolean;
            /** Revision */
            revision: number;
            current_state?: components["schemas"]["ProcessStateLabel"] | null;
            /** State Confidence */
            state_confidence?: number | null;
            /** State Observed At */
            state_observed_at?: string | null;
            state?: components["schemas"]["ProcessStateOut"] | null;
            /** Open Bottlenecks */
            open_bottlenecks?: components["schemas"]["BottleneckOut"][];
            /** Open Critiques */
            open_critiques?: components["schemas"]["CritiqueOut"][];
            /**
             * Evidence Event Count
             * @default 0
             */
            evidence_event_count: number;
            /**
             * Contradicting Event Count
             * @default 0
             */
            contradicting_event_count: number;
        };
        /**
         * ProcessStateLabel
         * @description Every categorical State across all Archetypes.
         *
         *     A flat vocabulary keeps the database column typed; ``StateMachine`` enforces
         *     which labels are legal for which Archetype.
         * @enum {string}
         */
        ProcessStateLabel: "discovery" | "early_adoption" | "acceleration" | "infrastructure_expansion" | "saturation" | "maturity" | "weak_demand" | "demand_recovery" | "inventory_draw" | "supply_tightness" | "price_acceleration" | "supply_response" | "oversupply" | "downcycle" | "constraint_emerging" | "constraint_binding" | "response_mobilization" | "buildout" | "capacity_delivery" | "constraint_relieved" | "announced" | "enacted" | "rulemaking" | "implementation" | "compliance_buildout" | "enforcement" | "normalization" | "trigger" | "experimentation" | "behavior_shift" | "substitution" | "incumbent_response" | "reallocation" | "new_equilibrium";
        /** ProcessStateOut */
        ProcessStateOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            archetype: components["schemas"]["ProcessArchetype"];
            categorical_state: components["schemas"]["ProcessStateLabel"];
            /** State Confidence */
            state_confidence: number;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Features */
            features?: components["schemas"]["StateFeatureOut"][];
            /**
             * Transition Beliefs
             * @description Model belief that the Process moves next to each State. Not probabilities: uncalibrated until the calibration framework validates them (ontology §35).
             */
            transition_beliefs?: {
                [key: string]: number;
            };
            /** Transition Indicators */
            transition_indicators?: string[];
            /** Reversal Indicators */
            reversal_indicators?: string[];
        };
        /**
         * ProcessStatus
         * @description Lifecycle of the Process object itself, distinct from its economic
         *     State (ontology §7 vs §10).
         * @enum {string}
         */
        ProcessStatus: "candidate" | "active" | "dormant" | "invalidated" | "merged" | "concluded";
        /** ProcessSummaryOut */
        ProcessSummaryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description: string;
            archetype: components["schemas"]["ProcessArchetype"] | null;
            /** Archetype Confidence */
            archetype_confidence: number | null;
            status: components["schemas"]["ProcessStatus"];
            /** Requires Review */
            requires_review: boolean;
            /** Revision */
            revision: number;
            current_state?: components["schemas"]["ProcessStateLabel"] | null;
            /** State Confidence */
            state_confidence?: number | null;
            /** State Observed At */
            state_observed_at?: string | null;
        };
        /** QueueDepthOut */
        QueueDepthOut: {
            /** Stage */
            stage: string | null;
            /** Pending */
            pending: number;
            /** Running */
            running: number;
            /** Failed */
            failed: number;
            /** Dead */
            dead: number;
        };
        /**
         * RelationshipType
         * @description Typed edges (ui_concept §9.1).
         *
         *     The canonical chain is::
         *
         *         Process --influences--> Process
         *         Process --creates--> Bottleneck
         *         Bottleneck --requires--> Capability
         *         Capability --expressed_by--> Asset
         *
         *     Additional types carry evidence and direct Event exposure (ontology §15).
         * @enum {string}
         */
        RelationshipType: "influences" | "creates" | "requires" | "expressed_by" | "affects" | "supports" | "contradicts" | "supersedes" | "derived_from";
        /**
         * RequirementNodeOut
         * @description One node of a requirement tree.
         *
         *     Returned as a tree rather than a flat list because AND and OR imply
         *     completely different sets of participants (ontology §12), and flattening for
         *     transport would discard the distinction the mapping agent was asked for.
         */
        RequirementNodeOut: {
            /** Kind */
            kind: string;
            operator?: components["schemas"]["LogicOperator"] | null;
            /** Label */
            label?: string | null;
            capability?: components["schemas"]["NodeRef"] | null;
            necessity: components["schemas"]["Necessity"];
            /** Weight */
            weight: number;
            /** Children */
            children?: components["schemas"]["RequirementNodeOut"][];
        };
        /** RequirementOut */
        RequirementOut: {
            /**
             * Bottleneck Id
             * Format: uuid
             */
            bottleneck_id: string;
            /** Revision */
            revision: number;
            root: components["schemas"]["RequirementNodeOut"];
            /** Capability Count */
            capability_count: number;
        };
        /** ScoreDimensionOut */
        ScoreDimensionOut: {
            /** Dimension */
            dimension: string;
            /** Value */
            value: number;
            /** Confidence */
            confidence: number;
            /** Method */
            method: string;
            /**
             * Inputs
             * @description What the value was computed from.
             */
            inputs?: {
                [key: string]: number;
            };
            /** Rationale */
            rationale?: string | null;
        };
        /**
         * ScoreFamily
         * @description Ontology §17. These three are never collapsed into one number, anywhere.
         *
         *     Trade quality is V2 and is present only so that stored scores can never be
         *     mislabelled; nothing in V1 produces it.
         * @enum {string}
         */
        ScoreFamily: "thesis_quality" | "asset_quality" | "trade_quality";
        /**
         * ScorecardOut
         * @description One family, never a blend.
         *
         *     Thesis, Asset and Trade quality are separate by construction (ontology §17),
         *     and there is deliberately no endpoint that combines them.
         */
        ScorecardOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            subject: components["schemas"]["NodeRef"];
            family: components["schemas"]["ScoreFamily"];
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Composite */
            composite: number | null;
            /** Composite Method */
            composite_method: string | null;
            /** Dimensions */
            dimensions?: components["schemas"]["ScoreDimensionOut"][];
        };
        /** StateFeatureOut */
        StateFeatureOut: {
            /** Name */
            name: string;
            /** Value */
            value: number;
            /**
             * Basis
             * @description 'measured' or 'estimated' — whether code computed it or an agent judged it.
             */
            basis: string;
            /** Rationale */
            rationale?: string | null;
        };
        /** SubgraphOut */
        SubgraphOut: {
            /** Nodes */
            nodes?: components["schemas"]["GraphNodeOut"][];
            /** Edges */
            edges?: components["schemas"]["GraphEdgeOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    list_processes_api_processes_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ProcessStatus"][] | null;
                requires_review?: boolean | null;
                limit?: number;
                offset?: number;
                /** @description Reconstruct the graph as it was at this instant. Omit for the current state. Revisions and observations recorded later are excluded, so a replay describes what was believed then. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_process_api_processes__process_id__get: {
        parameters: {
            query?: {
                /** @description Reconstruct the graph as it was at this instant. Omit for the current state. Revisions and observations recorded later are excluded, so a replay describes what was believed then. */
                as_of?: string | null;
            };
            header?: never;
            path: {
                process_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    state_history_api_processes__process_id__states_get: {
        parameters: {
            query?: {
                /** @description Reconstruct the graph as it was at this instant. Omit for the current state. Revisions and observations recorded later are excluded, so a replay describes what was believed then. */
                as_of?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                process_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessStateOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    journal_api_processes__process_id__journal_get: {
        parameters: {
            query?: {
                /** @description Reconstruct the graph as it was at this instant. Omit for the current state. Revisions and observations recorded later are excluded, so a replay describes what was believed then. */
                as_of?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                process_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    critiques_api_processes__process_id__critiques_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["CritiqueStatus"][] | null;
                /** @description Reconstruct the graph as it was at this instant. Omit for the current state. Revisions and observations recorded later are excluded, so a replay describes what was believed then. */
                as_of?: string | null;
            };
            header?: never;
            path: {
                process_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CritiqueOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_events_get: {
        parameters: {
            query?: {
                event_type?: components["schemas"]["EventType"][] | null;
                /** @description Only Events that cleared the significance gate. */
                propagated_only?: boolean;
                min_materiality?: number | null;
                limit?: number;
                offset?: number;
                /** @description Reconstruct the graph as it was at this instant. Omit for the current state. Revisions and observations recorded later are excluded, so a replay describes what was believed then. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_api_events__event_id__get: {
        parameters: {
            query?: {
                /** @description Reconstruct the graph as it was at this instant. Omit for the current state. Revisions and observations recorded later are excluded, so a replay describes what was believed then. */
                as_of?: string | null;
            };
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evidence_trail_api_evidence__node_id__get: {
        parameters: {
            query?: {
                /** @description Reconstruct the graph as it was at this instant. Omit for the current state. Revisions and observations recorded later are excluded, so a replay describes what was believed then. */
                as_of?: string | null;
            };
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceTrailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bottlenecks_api_bottlenecks_get: {
        parameters: {
            query?: {
                /** @description Only constraints that bind now, not ones that would later. */
                binding_only?: boolean;
                process_id?: string | null;
                limit?: number;
                offset?: number;
                /** @description Reconstruct the graph as it was at this instant. Omit for the current state. Revisions and observations recorded later are excluded, so a replay describes what was believed then. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BottleneckOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bottleneck_api_bottlenecks__bottleneck_id__get: {
        parameters: {
            query?: {
                /** @description Reconstruct the graph as it was at this instant. Omit for the current state. Revisions and observations recorded later are excluded, so a replay describes what was believed then. */
                as_of?: string | null;
            };
            header?: never;
            path: {
                bottleneck_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BottleneckOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_requirements_api_bottlenecks__bottleneck_id__requirements_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bottleneck_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_capabilities_api_capabilities_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Reconstruct the graph as it was at this instant. Omit for the current state. Revisions and observations recorded later are excluded, so a replay describes what was believed then. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_capability_api_capabilities__capability_id__get: {
        parameters: {
            query?: {
                /** @description Reconstruct the graph as it was at this instant. Omit for the current state. Revisions and observations recorded later are excluded, so a replay describes what was believed then. */
                as_of?: string | null;
            };
            header?: never;
            path: {
                capability_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assets_api_assets_get: {
        parameters: {
            query?: {
                asset_class?: components["schemas"]["AssetClass"][] | null;
                limit?: number;
                offset?: number;
                /** @description Reconstruct the graph as it was at this instant. Omit for the current state. Revisions and observations recorded later are excluded, so a replay describes what was believed then. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_asset_api_assets__asset_id__get: {
        parameters: {
            query?: {
                max_hops?: number;
                /** @description Reconstruct the graph as it was at this instant. Omit for the current state. Revisions and observations recorded later are excluded, so a replay describes what was believed then. */
                as_of?: string | null;
            };
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discovery_chain_api_assets__asset_id__discovery_chain_get: {
        parameters: {
            query?: {
                max_hops?: number;
                /** @description Reconstruct the graph as it was at this instant. Omit for the current state. Revisions and observations recorded later are excluded, so a replay describes what was believed then. */
                as_of?: string | null;
            };
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryPathOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    asset_reach_api_graph_reach_get: {
        parameters: {
            query: {
                process_id: string[];
                max_hops?: number;
                limit?: number;
                /** @description Reconstruct the graph as it was at this instant. Omit for the current state. Revisions and observations recorded later are excluded, so a replay describes what was believed then. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetReachOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subgraph_api_graph_subgraph_get: {
        parameters: {
            query: {
                node_id: string[];
                depth?: number;
                limit?: number;
                /** @description Reconstruct the graph as it was at this instant. Omit for the current state. Revisions and observations recorded later are excluded, so a replay describes what was believed then. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubgraphOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    paths_api_graph_paths_get: {
        parameters: {
            query: {
                node_id: string[];
                direction?: components["schemas"]["Direction"];
                max_hops?: number;
                limit?: number;
                /** @description Reconstruct the graph as it was at this instant. Omit for the current state. Revisions and observations recorded later are excluded, so a replay describes what was believed then. */
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryPathOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    integrity_api_graph_integrity_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrityReportOut"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                agent_name?: string[] | null;
                status?: string[] | null;
                /** @description Only runs whose output was refused by a deterministic check. */
                failed_evaluation?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scores_api_scores__subject_id__get: {
        parameters: {
            query?: {
                family?: components["schemas"]["ScoreFamily"][] | null;
                /** @description Reconstruct the graph as it was at this instant. Omit for the current state. Revisions and observations recorded later are excluded, so a replay describes what was believed then. */
                as_of?: string | null;
            };
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScorecardOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pipeline_api_pipeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineStageOut"][];
                };
            };
        };
    };
    queue_depth_api_pipeline_queue_get: {
        parameters: {
            query?: {
                stage?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueDepthOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
