"""counterfactuals

Revision ID: 7275146c7c2c
Revises: 0a323353553e
Create Date: 2026-08-08 01:12:29.740011+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '7275146c7c2c'
down_revision: str | None = '0a323353553e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counterfactuals',
    sa.Column('counterfactual_id', sa.UUID(), nullable=False),
    sa.Column('process_id', sa.UUID(), nullable=False),
    sa.Column('challenged_assumption', sa.Text(), nullable=False),
    sa.Column('alternative_world', sa.Text(), nullable=False),
    sa.Column('affected_links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assets_harmed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observable_indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plausibility', sa.Float(), nullable=False),
    sa.Column('severity_if_true', sa.Float(), nullable=False),
    sa.Column('is_most_dangerous', sa.Boolean(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True, comment='Set when a later run replaced this set. Never deleted.'),
    sa.Column('supporting_claim_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('plausibility >= 0 AND plausibility <= 10', name=op.f('ck_counterfactuals_plausibility_range')),
    sa.CheckConstraint('severity_if_true >= 0 AND severity_if_true <= 10', name=op.f('ck_counterfactuals_severity_range')),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.agent_run_id'], name=op.f('fk_counterfactuals_agent_run_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['process_id'], ['nodes.node_id'], name=op.f('fk_counterfactuals_process_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('counterfactual_id', name=op.f('pk_counterfactuals'))
    )
    op.create_index(op.f('ix_counterfactuals_agent_run_id'), 'counterfactuals', ['agent_run_id'], unique=False)
    op.create_index('ix_counterfactuals_process', 'counterfactuals', ['process_id', 'superseded_at', 'observed_at'], unique=False)
    op.create_index(op.f('ix_counterfactuals_process_id'), 'counterfactuals', ['process_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_counterfactuals_process_id'), table_name='counterfactuals')
    op.drop_index('ix_counterfactuals_process', table_name='counterfactuals')
    op.drop_index(op.f('ix_counterfactuals_agent_run_id'), table_name='counterfactuals')
    op.drop_table('counterfactuals')
    # ### end Alembic commands ###
