"""workspaces and watchlists

Revision ID: 78a4a1926b8a
Revises: f47db86bfc8f
Create Date: 2026-08-08 03:07:20.585332+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision: str = '78a4a1926b8a'
down_revision: str | None = 'f47db86bfc8f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False, comment="'personal' or 'organization'."),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('personal','organization')", name=op.f('ck_workspaces_kind_known')),
    sa.PrimaryKeyConstraint('workspace_id', name=op.f('pk_workspaces')),
    sa.UniqueConstraint('external_id', name=op.f('uq_workspaces_external_id'))
    )
    op.create_table('watchlist_items',
    sa.Column('watchlist_item_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    # The type already exists; recreating it fails on "already exists".
    sa.Column(
        'node_type',
        postgresql.ENUM(name='entity_type', create_type=False),
        nullable=False,
    ),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('added_by', sa.String(length=128), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True, comment='Un-watching is a dated fact, not a delete: when someone stopped caring is part of the research record.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], name=op.f('fk_watchlist_items_node_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], name=op.f('fk_watchlist_items_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('watchlist_item_id', name=op.f('pk_watchlist_items'))
    )
    op.create_index(op.f('ix_watchlist_items_node_id'), 'watchlist_items', ['node_id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_workspace_id'), 'watchlist_items', ['workspace_id'], unique=False)
    op.create_index('uq_watchlist_active', 'watchlist_items', ['workspace_id', 'node_id'], unique=True, postgresql_where=sa.text('removed_at IS NULL'))
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('external_user_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner','admin','member','viewer')", name=op.f('ck_workspace_members_role_known')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], name=op.f('fk_workspace_members_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'external_user_id', name=op.f('pk_workspace_members'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_members')
    op.drop_index('uq_watchlist_active', table_name='watchlist_items', postgresql_where=sa.text('removed_at IS NULL'))
    op.drop_index(op.f('ix_watchlist_items_workspace_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_node_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
