"""evidence dependence graph

Revision ID: f47db86bfc8f
Revises: 7275146c7c2c
Create Date: 2026-08-08 01:46:57.769420+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f47db86bfc8f'
down_revision: str | None = '7275146c7c2c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_dependencies',
    sa.Column('evidence_dependence_id', sa.UUID(), nullable=False),
    sa.Column('process_id', sa.UUID(), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.Column('dependent_event_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('shared_source', 'derivative_reporting', 'repeated_claim', name='evidence_dependence_kind'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detected_by', sa.String(length=16), nullable=False, comment="'computed' or 'judged' — whether code or an agent found it."),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source_event_id <> dependent_event_id', name=op.f('ck_evidence_dependencies_no_self_dependence')),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.agent_run_id'], name=op.f('fk_evidence_dependencies_agent_run_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dependent_event_id'], ['nodes.node_id'], name=op.f('fk_evidence_dependencies_dependent_event_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['process_id'], ['nodes.node_id'], name=op.f('fk_evidence_dependencies_process_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_event_id'], ['nodes.node_id'], name=op.f('fk_evidence_dependencies_source_event_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('evidence_dependence_id', name=op.f('pk_evidence_dependencies'))
    )
    op.create_index(op.f('ix_evidence_dependencies_agent_run_id'), 'evidence_dependencies', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_evidence_dependencies_dependent_event_id'), 'evidence_dependencies', ['dependent_event_id'], unique=False)
    op.create_index(op.f('ix_evidence_dependencies_kind'), 'evidence_dependencies', ['kind'], unique=False)
    op.create_index('ix_evidence_dependencies_process', 'evidence_dependencies', ['process_id', 'superseded_at'], unique=False)
    op.create_index(op.f('ix_evidence_dependencies_process_id'), 'evidence_dependencies', ['process_id'], unique=False)
    op.create_index(op.f('ix_evidence_dependencies_source_event_id'), 'evidence_dependencies', ['source_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_dependencies_source_event_id'), table_name='evidence_dependencies')
    op.drop_index(op.f('ix_evidence_dependencies_process_id'), table_name='evidence_dependencies')
    op.drop_index('ix_evidence_dependencies_process', table_name='evidence_dependencies')
    op.drop_index(op.f('ix_evidence_dependencies_kind'), table_name='evidence_dependencies')
    op.drop_index(op.f('ix_evidence_dependencies_dependent_event_id'), table_name='evidence_dependencies')
    op.drop_index(op.f('ix_evidence_dependencies_agent_run_id'), table_name='evidence_dependencies')
    op.drop_table('evidence_dependencies')
    # SQLAlchemy creates the enum type with the table but does not drop it, so
    # a down-then-up round trip fails on "type already exists" without this.
    op.execute("DROP TYPE IF EXISTS evidence_dependence_kind")
    # ### end Alembic commands ###
