"""Canonical ontology for the econiq research platform.

This package is the contract between the database, the agents, the API and the
frontend. Nothing downstream may define its own version of these objects.

The chain (ontology §3)::

    Document → Claim → Event → Process → Process State
    → Bottleneck → Capability Requirement → Asset Candidate → Asset → Asset State
"""

from econiq_ontology.archetypes import (
    STATE_MACHINES,
    UNSPECIFIED_IN_SOURCE,
    ProcessStateLabel,
    StateMachine,
    state_machine,
    states_for,
    validate_state,
)
from econiq_ontology.asset_layer import (
    Asset,
    AssetCandidate,
    AssetExposure,
    AssetIdentifiers,
    AssetState,
    FundamentalState,
    MarketStructureState,
    TechnicalState,
    ValuationState,
)
from econiq_ontology.base import (
    ONTOLOGY_SCHEMA_VERSION,
    Confidence,
    Entity,
    OntologyModel,
    Score10,
    TemporalObservation,
    Weight,
    new_id,
    utcnow,
)
from econiq_ontology.enums import (
    AssetClass,
    AssetQualityDimension,
    BottleneckKind,
    CausalRole,
    ClaimType,
    DocumentType,
    EntityType,
    EpistemicStatus,
    EventType,
    ExposureKind,
    ExtractionStatus,
    LogicOperator,
    Necessity,
    ProcessArchetype,
    ProcessStatus,
    RelationshipType,
    ScoreFamily,
    ThesisQualityDimension,
)
from econiq_ontology.evidence_layer import Claim, Document, EntityMention, Event
from econiq_ontology.graph import ALLOWED_EDGES, Relationship, edge_is_legal
from econiq_ontology.process_layer import (
    Bottleneck,
    BottleneckMetrics,
    Capability,
    CapabilityLeaf,
    CapabilityRequirement,
    Process,
    ProcessState,
    RequirementGroup,
    RequirementNode,
    StateFeature,
)
from econiq_ontology.provenance import (
    AgentAttribution,
    EntityRef,
    EvidenceRef,
    SourceLocation,
)
from econiq_ontology.quality import (
    FAMILY_DIMENSIONS,
    FAMILY_SUBJECTS,
    DimensionScore,
    Scorecard,
)

__all__ = [
    "ALLOWED_EDGES",
    "FAMILY_DIMENSIONS",
    "FAMILY_SUBJECTS",
    "ONTOLOGY_SCHEMA_VERSION",
    "STATE_MACHINES",
    "UNSPECIFIED_IN_SOURCE",
    "AgentAttribution",
    "Asset",
    "AssetCandidate",
    "AssetClass",
    "AssetExposure",
    "AssetIdentifiers",
    "AssetQualityDimension",
    "AssetState",
    "Bottleneck",
    "BottleneckKind",
    "BottleneckMetrics",
    "Capability",
    "CapabilityLeaf",
    "CapabilityRequirement",
    "CausalRole",
    "Claim",
    "ClaimType",
    "Confidence",
    "DimensionScore",
    "Document",
    "DocumentType",
    "Entity",
    "EntityMention",
    "EntityRef",
    "EntityType",
    "EpistemicStatus",
    "Event",
    "EventType",
    "EvidenceRef",
    "ExposureKind",
    "ExtractionStatus",
    "FundamentalState",
    "LogicOperator",
    "MarketStructureState",
    "Necessity",
    "OntologyModel",
    "Process",
    "ProcessArchetype",
    "ProcessState",
    "ProcessStateLabel",
    "ProcessStatus",
    "Relationship",
    "RelationshipType",
    "RequirementGroup",
    "RequirementNode",
    "Score10",
    "ScoreFamily",
    "Scorecard",
    "SourceLocation",
    "StateFeature",
    "StateMachine",
    "TechnicalState",
    "TemporalObservation",
    "ThesisQualityDimension",
    "ValuationState",
    "Weight",
    "edge_is_legal",
    "new_id",
    "state_machine",
    "states_for",
    "utcnow",
    "validate_state",
]
